name: Habesha Sport News Bot

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: habesha-sport-bot
  cancel-in-progress: false

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Download bot files
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Run Telegram bot
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          USER_SESSION: ${{ secrets.USER_SESSION }}

          FB_ETHIO_SPORT_PAGE_ID: ${{ secrets.FB_ETHIO_SPORT_PAGE_ID }}
          FB_ETHIO_SPORT_PAGE_TOKEN: ${{ secrets.FB_ETHIO_SPORT_PAGE_TOKEN }}

          FB_ARSENAL_PAGE_ID: ${{ secrets.FB_ARSENAL_PAGE_ID }}
          FB_ARSENAL_PAGE_TOKEN: ${{ secrets.FB_ARSENAL_PAGE_TOKEN }}

        run: |
          python -u github_bot.py

      - name: Save bot state
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add state.json

          if git diff --cached --quiet; then
            echo "No state changes"
          else
            git commit -m "Update bot state"
            git pull --rebase origin main
            git push origin main
          fi
